version: '3.8'

services:
  laravel:
    build:
      dockerfile: ./Dockerfile
    platform: linux/amd64
    volumes:
      - laravel-volume:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      db-zurich:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      timeout: 3s
      retries: 10

  db-zurich:
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_ZURICH}
      - MYSQL_USER=${DB_USERNAME_ZURICH}
      - MYSQL_PASSWORD=${DB_PASSWORD_ZURICH}
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "${DB_PORT_ZURICH}"
    volumes:
      - db-zurich-data:/var/lib/mysql
      - ./ZURICH.sql:/docker-entrypoint-initdb.d/ZURICH.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-c", "1"]
      timeout: 3s
      retries: 10
  
  nginx:
    image: nginx:latest
    platform: linux/amd64
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - laravel-volume:/usr/src/app
    ports:
      - "80:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    depends_on:
      laravel:
        condition: service_healthy

volumes:
  laravel-volume:
  db-zurich-data:
